<?php
/**
 * NoDB-WebBase
 * GitHub: https://github.com/max-godman
 *
 * SQL Helper Functions
 * Used by adm/sys.php?type=sql for database management
 *
 * @package NoDB-WebBase
 * @since 2026-05-13
 */

/**
 * Read database config from sys_sql.php
 * @return array Config array with keys: db_name, db_host, db_user, db_pass, db_charset
 */
function getSqlConfig() {
    $configFile = __DIR__ . '/sys_sql.php';
    if (!file_exists($configFile)) {
        return [
            'db_name' => '',
            'db_host' => 'localhost',
            'db_user' => '',
            'db_pass' => '',
            'db_charset' => 'utf8mb4',
        ];
    }
    $cfg = include $configFile;
    if (!is_array($cfg)) {
        return [
            'db_name' => '',
            'db_host' => 'localhost',
            'db_user' => '',
            'db_pass' => '',
            'db_charset' => 'utf8mb4',
        ];
    }
    return $cfg;
}

/**
 * Write database config to sys_sql.php
 * @param string $dbName Database name
 * @param string $dbHost Database host
 * @param string $dbUser Database username
 * @param string $dbPass Database password
 * @return bool Success
 */
function writeSqlConfig($dbName, $dbHost, $dbUser, $dbPass) {
    $configFile = __DIR__ . '/sys_sql.php';
    $content = "<?php\n"
        . "/**\n"
        . " * NoDB-WebBase\n"
        . " * GitHub: https://github.com/max-godman\n"
        . " *\n"
        . " * Database Configuration\n"
        . " * Auto-generated by SQL Manager\n"
        . " * @package NoDB-WebBase\n"
        . " */\n\n"
        . "return [\n"
        . "    'db_name'    => " . var_export($dbName, true) . ",\n"
        . "    'db_host'    => " . var_export($dbHost, true) . ",\n"
        . "    'db_user'    => " . var_export($dbUser, true) . ",\n"
        . "    'db_pass'    => " . var_export($dbPass, true) . ",\n"
        . "    'db_charset' => 'utf8mb4',\n"
        . "];\n";
    return file_put_contents($configFile, $content, LOCK_EX) !== false;
}

/**
 * Test database connection with given config
 * @param array $config Config array
 * @return array ['success' => bool, 'message' => string, 'pdo' => PDO|null]
 */
function testDbConnection($config) {
    if (empty($config['db_name']) || empty($config['db_host']) || empty($config['db_user'])) {
        return ['success' => false, 'message' => 'Database configuration incomplete', 'pdo' => null];
    }
    try {
        $dsn = 'mysql:host=' . $config['db_host'] . ';dbname=' . $config['db_name'] . ';charset=' . ($config['db_charset'] ?? 'utf8mb4');
        $pdo = new PDO($dsn, $config['db_user'], $config['db_pass']);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
        return ['success' => true, 'message' => 'Connection successful', 'pdo' => $pdo];
    } catch (PDOException $e) {
        return ['success' => false, 'message' => 'Connection failed: ' . $e->getMessage(), 'pdo' => null];
    }
}

/**
 * Read protected tables list
 * @return array ['tablename' => level, ...]
 */
function getProtectedTables() {
    $file = __DIR__ . '/../data/sql_protected.log';
    $result = [];
    if (!file_exists($file)) {
        return $result;
    }
    $lines = file($file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    foreach ($lines as $line) {
        $line = trim($line);
        if (empty($line) || $line[0] === '#') continue;
        $parts = explode('|', $line);
        if (count($parts) >= 2) {
            $level = intval(trim($parts[0]));
            $table = trim($parts[1]);
            if (!empty($table)) {
                $result[$table] = $level;
            }
        }
    }
    return $result;
}

/**
 * Get permission level for a specific table
 * @param string $tableName
 * @return int|null Level or null if not in protected list
 */
function getTablePermission($tableName) {
    $tables = getProtectedTables();
    return isset($tables[$tableName]) ? $tables[$tableName] : null;
}

/**
 * Add a table to the protected list
 * @param string $tableName
 * @param int $level Default 8
 * @return bool Success
 */
function addProtectedTable($tableName, $level = 8) {
    $file = __DIR__ . '/../data/sql_protected.log';
    $existing = getProtectedTables();
    if (isset($existing[$tableName])) {
        return true;
    }
    $content = '';
    if (file_exists($file)) {
        $content = file_get_contents($file);
    }
    if (!empty($content) && substr($content, -1) !== "\n") {
        $content .= "\n";
    }
    $content .= $level . '|' . $tableName . "\n";
    return file_put_contents($file, $content, LOCK_EX) !== false;
}

/**
 * Detect SQL statement type
 * @param string $sql
 * @return string Type: SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, TRUNCATE, SHOW, DESCRIBE, REPLACE, UNKNOWN
 */
function getStatementType($sql) {
    $sql = trim($sql);
    if (empty($sql)) return 'UNKNOWN';

    $firstWord = strtoupper(strtok($sql, " \t\n\r\0\x0B("));
    $knownTypes = ['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'CREATE', 'ALTER', 'DROP', 'TRUNCATE', 'SHOW', 'DESCRIBE', 'EXPLAIN', 'REPLACE', 'RENAME', 'CALL', 'SET', 'BEGIN', 'COMMIT', 'ROLLBACK', 'START', 'SAVEPOINT', 'LOCK', 'UNLOCK', 'GRANT', 'REVOKE', 'OPTIMIZE', 'ANALYZE', 'CHECK', 'REPAIR', 'USE'];

    if (in_array($firstWord, $knownTypes)) {
        return $firstWord;
    }

    // Maybe starts with ( for SELECT without keyword
    if ($firstWord === '(') {
        return 'SELECT';
    }

    return 'UNKNOWN';
}

/**
 * Extract table names from SQL statement
 * @param string $sql
 * @return array Array of table names
 */
function extractTableName($sql) {
    $sql = trim($sql);
    if (empty($sql)) return [];
    $type = getStatementType($sql);
    $tables = [];

    switch ($type) {
        case 'SELECT':
        case 'INSERT':
        case 'REPLACE':
        case 'UPDATE':
        case 'DELETE':
            // Extract FROM clause for SELECT/DELETE, INTO for INSERT, TABLE for UPDATE
            if (preg_match('~\bFROM\s+`?(\w+)`?\b~i', $sql, $m)) {
                $tables[] = $m[1];
            }
            if (preg_match('~\bINTO\s+`?(\w+)`?\b~i', $sql, $m)) {
                $tables[] = $m[1];
            }
            if (preg_match('~\bUPDATE\s+`?(\w+)`?\b~i', $sql, $m)) {
                $tables[] = $m[1];
            }
            if (preg_match('~\bJOIN\s+`?(\w+)`?\b~i', $sql, $m)) {
                $tables[] = $m[1];
            }
            // Also check TABLE keyword
            if (preg_match('~\bTABLE\s+`?(\w+)`?\b~i', $sql, $m)) {
                $tables[] = $m[1];
            }
            break;

        case 'CREATE':
            if (preg_match('~\bTABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?`?(\w+)`?\b~i', $sql, $m)) {
                $tables[] = $m[1];
            }
            break;

        case 'ALTER':
        case 'DROP':
        case 'TRUNCATE':
            if (preg_match('~\bTABLE\s+(?:IF\s+EXISTS\s+)?`?(\w+)`?\b~i', $sql, $m)) {
                $tables[] = $m[1];
            }
            break;

        case 'DESCRIBE':
        case 'EXPLAIN':
            if (preg_match('~\bDESCRIBE\s+`?(\w+)`?\b~i', $sql, $m)) {
                $tables[] = $m[1];
            }
            if (preg_match('~\bEXPLAIN\s+`?(\w+)`?\b~i', $sql, $m)) {
                $tables[] = $m[1];
            }
            break;

        case 'SHOW':
            if (preg_match('~(?:FROM|IN)\s+`?(\w+)`?\b~i', $sql, $m)) {
                $tables[] = $m[1];
            }
            break;

        case 'RENAME':
            if (preg_match('~\bTABLE\s+`?(\w+)`?\b~i', $sql, $m)) {
                $tables[] = $m[1];
            }
            break;
    }

    return array_unique(array_filter($tables));
}

/**
 * Check if the operation is allowed on given tables
 * @param string $stmtType SQL statement type
 * @param array $tables Array of table names
 * @return array ['allow' => bool, 'reason' => string, 'required_level' => int|null]
 */
function checkTablePermission($stmtType, $tables) {
    $typeUpper = strtoupper($stmtType);

    // Statements that don't operate on tables or are always allowed
    $noTableTypes = ['SET', 'BEGIN', 'COMMIT', 'ROLLBACK', 'START', 'SAVEPOINT', 'USE'];
    if (in_array($typeUpper, $noTableTypes)) {
        return ['allow' => true, 'reason' => '', 'required_level' => null];
    }

    // CREATE TABLE is always allowed
    if ($typeUpper === 'CREATE') {
        return ['allow' => true, 'reason' => '', 'required_level' => null];
    }

    // If no tables involved, allow
    if (empty($tables)) {
        // SHOW TABLES, SELECT 1, etc.
        if (in_array($typeUpper, ['SHOW', 'SELECT', 'UNKNOWN'])) {
            return ['allow' => true, 'reason' => '', 'required_level' => null];
        }
        return ['allow' => false, 'reason' => 'Could not determine target table', 'required_level' => null];
    }

    // Determine required level
    $requiredLevel = null;
    switch ($typeUpper) {
        case 'DROP':
        case 'RENAME':
            $requiredLevel = 10;
            break;
        case 'ALTER':
        case 'TRUNCATE':
            $requiredLevel = 9;
            break;
        case 'INSERT':
        case 'UPDATE':
        case 'DELETE':
        case 'REPLACE':
        case 'CALL':
            $requiredLevel = 8;
            break;
        case 'SELECT':
        case 'SHOW':
        case 'DESCRIBE':
        case 'EXPLAIN':
        case 'OPTIMIZE':
        case 'ANALYZE':
        case 'CHECK':
        case 'REPAIR':
            $requiredLevel = 5;
            break;
        default:
            $requiredLevel = 10;
            break;
    }

    $protected = getProtectedTables();
    $missingTables = [];
    $lowestLevel = 999;

    foreach ($tables as $table) {
        if (!isset($protected[$table])) {
            $missingTables[] = $table;
        } else {
            if ($protected[$table] < $lowestLevel) {
                $lowestLevel = $protected[$table];
            }
        }
    }

    if (!empty($missingTables)) {
        return [
            'allow' => false,
            'reason' => 'Table(s) not in protected list: ' . implode(', ', $missingTables) . '. Add them via File Editor first.',
            'required_level' => $requiredLevel
        ];
    }

    if ($lowestLevel < $requiredLevel) {
        return [
            'allow' => false,
            'reason' => 'Insufficient permission. Need level ' . $requiredLevel . ' for operation "' . $typeUpper . '", but table(s) only have level ' . $lowestLevel . '.',
            'required_level' => $requiredLevel
        ];
    }

    return ['allow' => true, 'reason' => '', 'required_level' => $requiredLevel];
}

/**
 * Execute a single SQL statement and return structured result
 * @param PDO $pdo
 * @param string $sql
 * @return array Structured result
 */
function executeSqlStatement($pdo, $sql) {
    $sql = trim($sql);
    if (empty($sql)) {
        return ['success' => false, 'type' => 'UNKNOWN', 'message' => 'SQL is empty', 'data' => [], 'columns' => [], 'affected_rows' => 0, 'error' => 'Empty SQL'];
    }

    $type = getStatementType($sql);
    $tables = extractTableName($sql);
    $result = [
        'success' => false,
        'type' => $type,
        'message' => '',
        'data' => [],
        'columns' => [],
        'affected_rows' => 0,
        'error' => '',
        'table' => !empty($tables) ? $tables[0] : '',
    ];

    try {
        $typeUpper = strtoupper($type);

        // For SELECT, SHOW, DESCRIBE, EXPLAIN use query() and fetch
        if (in_array($typeUpper, ['SELECT', 'SHOW', 'DESCRIBE', 'EXPLAIN'])) {
            $stmt = $pdo->query($sql);
            $result['data'] = $stmt->fetchAll(PDO::FETCH_ASSOC);
            $result['affected_rows'] = count($result['data']);

            // Get column names
            $colCount = $stmt->columnCount();
            $columns = [];
            for ($i = 0; $i < $colCount; $i++) {
                $colInfo = $stmt->getColumnMeta($i);
                $columns[] = $colInfo['name'] ?? 'col_' . $i;
            }
            $result['columns'] = $columns;

            $result['success'] = true;
            $result['message'] = 'Query returned ' . count($result['data']) . ' row(s)';
        } else {
            // For INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, TRUNCATE use exec()
            $affected = $pdo->exec($sql);
            $result['affected_rows'] = $affected !== false ? $affected : 0;
            $result['success'] = true;
            $result['message'] = 'Statement executed successfully. Affected rows: ' . $result['affected_rows'];
        }
    } catch (PDOException $e) {
        $result['success'] = false;
        $result['error'] = $e->getMessage();
        $result['message'] = 'Execution failed: ' . $e->getMessage();
    }

    return $result;
}

/**
 * Get a PDO connection from existing sys_sql.php config
 * @return array ['success' => bool, 'message' => string, 'pdo' => PDO|null]
 */
function getDbConnectionFromConfig() {
    $cfg = getSqlConfig();
    return testDbConnection($cfg);
}
