<?php
/**
 * NoDB-WebBase
 * GitHub: https://github.com/max-godman
 *
 * Database Configuration
 * Auto-generated by SQL Manager
 * @package NoDB-WebBase
 */

return [
    'db_name'    => 'db-name',
    'db_host'    => 'localhost',
    'db_user'    => 'db-user',
    'db_pass'    => 'YjK3n6btedhPAaKt',
    'db_charset' => 'utf8mb4',
];
