<?php
/**
 * NoDB-WebBase
 * GitHub: https://github.com/max-godman
 *
 * Database Configuration
 * Generated by setup.php. Edit values below then run setup to apply.
 *
 * @package NoDB-WebBase
 */

return [
    // Database name
    'db_name'    => '',
    // Database host (e.g. localhost)
    'db_host'    => 'localhost',
    // Database username
    'db_user'    => '',
    // Database password
    'db_pass'    => '',
    // Database charset
    'db_charset' => 'utf8mb4',
];
